export const LOADING_USERS = 'LOADING_USERS';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const LOADING_PLACES = 'LOADING_PLACES';
export const GET_ALL_PLACES = 'GET_ALL_PLACES';
export const GET_SINGLE_PLACE = 'GET_SINGLE_PLACE';